### ISSUE TITLE
improve LoginVC

### ISSUE THREAD

**Issue by bolom** [LordAlexWorks/guava.ios#96]
@SSamanta the code need to be improve

1. add comment for each function

Ex. What the purpose of **initilizeUITasks**

2. isPassedInFormValidation what do you thing about that https://github.com/steve228uk/SRFormValidator

3. pageOnLoginSuccess => replace by onLogOut

4. why you don't add the code callLoginController in isPassedInFormValidation directly what is the purpose to create a distinct function for that ? callLoginController() is called just on time

5. same question for pageOnLoginSuccess. Why you just call goToMain() ? You didn't call the api. When the user do a log out you have to call the api. The webservice will delete the token also in the backend

6. we can't keyboardWillShow and keyboardWillHide in external class ?

**Comment by SSamanta** [comment]
https://github.com/LordAlexWorks/guava/pull/109

**Comment by bolom** [comment]
Missing

- comments
